language: python
python:
  - 2.7
services:
  - docker
install:
  - cd featurette
  - pip install -r requirements.txt
  - pip install PyWebRunner
script:
  - sleep 50 # hard wait for docker compose
  - docker exec -it featurette_www_1 python -m unittest discover -v tests
  - webrunner tests/test_functional_login.yml
  - webrunner tests/test_functional_login_unauth.yml
  - webrunner tests/test_functional_add_client.yml
  - webrunner tests/test_functional_add_feature.yml
  - webrunner tests/test_functional_add_product_area.yml
# https://github.com/SeleniumHQ/selenium/blob/master/.travis.yml
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.12/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$PWD
  - sleep 3
  - docker-compose up -d
before_install:
  - export CHROMEDRIVER_BINARY=/usr/bin/chromium-browser
  - export CHROMEDRIVER_ARGS=--no-sandbox
  - /usr/bin/chromium-browser --version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_script:
  - docker-compose down
