language: python
python:
  - 2.7
services:
  - mysql
script:
  - cd featurette
  - pip install -r requirements.txt
  - python -m unittest discover tests
  - webrunner tests/test_functional_login.yml
  - webrunner tests/test_functional_login_unauth.yml
# http://stackoverflow.com/questions/20364674/chromedriver-on-travis-ci
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.9/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
