version: '2.1'
services:
  www:
    restart: always
    volumes:
      - /opt/Featurette/featurette:/opt/www/featurette
    build: .
    ports:
      - 5000:5000
    depends_on:
        db:
            condition: service_healthy
    links:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER_PASS=featurette:br1teCor3
      - PYTHONUNBUFFERED=1
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5000/login"]
        interval: 30s
        timeout: 10s
        retries: 5
  db:
    restart: always
    image: mysql:5.6
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: br1teCor3
      MYSQL_DATABASE: featurette
      MYSQL_USER: featurette
      MYSQL_PASSWORD: br1teCor3

  # isso:
  #   image: wonderfall/isso
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./isso:/config
  #     - ./isso:/db
