version: '2'
services:
    www:
        build: .
        ports:
            - 5000:5000
        depends_on:
            - db
        links:
            - db
        restart: always
    db:
        image: mysql:5.7
        volumes:
            - /var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: br1teCor3
            MYSQL_DATABASE: featurette
            MYSQL_USER: featurette
            MYSQL_PASSWORD: br1teCor3
